version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '4000:3000' # Map port 4000 on the host to port 3000 in the container
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      PUBLIK_KEY: reactdocker
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8060:80'
